### ISSUE TITLE
Jupyter notebook deployment from terminal: FileNotFoundError: [Errno 2] No such file or directory: 'quandl-wiki-tsla.json.gz'

### ISSUE THREAD

**Issue by cmougan** [rstudio/rsconnect#455]
I am deploying a jupyter notebook in the Rconnect by the conda terminal. I am using the example.
So I ran from the terminal
`rsconnect deploy notebook --server https://d-publish.space.tadnet.net --api-key XXXapikeyXXXX stock-report-jupyter.ipynb --new`

But in the demo example it says that a file has to be included as an Additional File 
![image](https://user-images.githubusercontent.com/43068386/93071421-6ccf6780-f680-11ea-82c8-5ae81c39dfef.png)
`

How do I add a file when deploying from command line? Is there any specific documentation or tutorial regarding this kind of deployment?

(base) C:\Users\navarra\Desktop\stock-report-jupyter>rsconnect deploy notebook --server https://d-publish.space.tadnet.net --api-key XXXXXXXXXX stock-report-jupyter.ipynb --new
Checking arguments...                            [OK]
    Deploying stock-report-jupyter.ipynb to server "https://d-publish.space.tadnet.net"
Inspecting Python environment...                 [OK]
Creating deployment bundle...                    [OK]
Uploading bundle...                              [OK]
Saving deployment data...                        [OK]

Deployment log:
Building Jupyter notebook...
Bundle requested Python version 3.8.3; using /mnt/share/conda/envs/kourou_rev1_python3.8/bin/python3.8 which has version 3.8.1
2020/09/14 11:28:15.720415661 arguments: /mnt/share/conda/envs/kourou_rev1_python3.8/bin/python3.8 /opt/rstudio-connect/python/build_environment.py
2020/09/14 11:28:15.720586014
2020/09/14 11:28:17.089029006
2020/09/14 11:28:17.089074165 CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
2020/09/14 11:28:17.089149492 To initialize your shell, run
2020/09/14 11:28:17.089156042
2020/09/14 11:28:17.089167494     $ conda init <SHELL_NAME>
2020/09/14 11:28:17.089168275
2020/09/14 11:28:17.089176022 Currently supported shells are:
2020/09/14 11:28:17.089176712   - bash
2020/09/14 11:28:17.089187898   - fish
2020/09/14 11:28:17.089188687   - tcsh
2020/09/14 11:28:17.089196563   - xonsh
2020/09/14 11:28:17.089197237   - zsh
2020/09/14 11:28:17.089205259   - powershell
2020/09/14 11:28:17.089205904
2020/09/14 11:28:17.089213614 See 'conda init --help' for more information and options.
2020/09/14 11:28:17.089216846
2020/09/14 11:28:17.089225279 IMPORTANT: You may need to close and restart your shell after running 'conda init'.
2020/09/14 11:28:17.089226038
2020/09/14 11:28:17.089233745
2020/09/14 11:28:17.429193292 Running on host: spaxd101.ecbt1.tadnet.net
2020/09/14 11:28:17.429238573 Environment will be built with Python "3.8.1 (default, Jan  8 2020, 22:29:32)  [GCC 7.3.0]" at /mnt/share/conda/envs/kourou_rev1_python3.8/bin/python3.8
2020/09/14 11:28:17.429624050 Running as user: rstudio-connect
2020/09/14 11:28:17.430823127 Using cached environment: iy9xLX--6JFMm47zyOI86w
2020/09/14 11:28:18.948235028 Packages in the environment: absl-py==0.9.0, alabaster==0.7.12, anaconda-client==1.7.2, anaconda-project==0.8.3, appdirs==1.4.3, argh==0.26.2, arrow==0.15.5, asn1crypto==1.3.0, astroid==2.3.3, astropy==4.0, astunparse==1.6.3, atomicwrites==1.3.0, attrs==19.3.0, autopep8==1.4.4, Babel==2.8.0, backcall==0.1.0, backports.shutil-get-terminal-size==1.0.0, bcrypt==3.2.0, beautifulsoup4==4.8.2, binaryornot==0.4.4, bitarray==1.2.1, bkcharts==0.2, bleach==3.1.0, bokeh==1.4.0, boto==2.49.0, boto3==1.12.46, botocore==1.15.46, Bottleneck==1.3.2, cachetools==4.1.0, certifi==2019.11.28, cffi==1.14.0, cfgv==3.1.0, chardet==3.0.4, Click==7.0, cloudpickle==1.3.0, clyent==1.2.2, colorama==0.4.3, contextlib2==0.6.0.post1, cookiecutter==1.7.2, cryptography==2.8, cycler==0.10.0, Cython==0.29.15, cytoolz==0.10.1, dask==2.11.0, dask-glm==0.2.0, dask-ml==1.6.0, dask-tensorflow==0.0.2, dask-xgboost==0.1.11, dask-yarn==0.8.1, decorator==4.4.1, defusedxml==0.6.0, diff-match-patch==20181111, distlib==0.3.0,
 distributed==2.11.0, docutils==0.15.2, elephas==0.4.3, entrypoints==0.3, et-xmlfile==1.0.1, fastcache==1.1.0, filelock==3.0.12, flake8==3.7.9, Flask==1.1.1, fsspec==0.6.2, future==0.18.2, fuzzywuzzy==0.18.0, gast==0.3.3, gensim==3.8.3, gevent==1.3.7, glob2==0.7, gmpy2==2.0.8, google-auth==1.14.1, google-auth-oauthlib==0.4.1, google-pasta==0.2.0, graphframes==0.6, greenlet==0.4.15, grpcio==1.28.1, h5py==2.10.0, HeapDict==1.0.1, html5lib==1.0.1, hyperas==0.4.1, hyperopt==0.2.4, hypothesis==5.5.4, identify==1.4.15, idna==2.8, imageio==2.6.1, imagesize==1.2.0, importlib-metadata==1.5.0, impyla==0.16.2, intervaltree==3.0.2, ipykernel==5.1.4, ipython==7.12.0, ipython-genutils==0.2.0, ipywidgets==7.5.1, isort==4.3.21, itsdangerous==1.1.0, jdcal==1.4.1, jedi==0.14.1, jeepney==0.4.2, Jinja2==2.11.1, jinja2-time==0.2.0, jmespath==0.9.5, joblib==0.14.1, json5==0.9.1, jsonschema==3.2.0, jupyter==1.0.0, jupyter-client==5.3.4, jupyter-console==6.1.0, jupyter-core==4.6.1, jupyterlab==1.2.6, jupyterlab-server==1.0.6, Keras=
=2.4.3, Keras-Applications==1.0.8, Keras-Preprocessing==1.1.2, keyring==21.1.0, kiwisolver==1.0.1, lazy-object-proxy==1.4.3, libarchive-c==2.8, llvmlite==0.31.0, locket==0.2.0, lxml==4.5.0, Markdown==3.2.1, MarkupSafe==1.1.1, matplotlib==3.1.3, mccabe==0.6.1, mistune==0.8.4, mkl-fft==1.0.15, mkl-random==1.1.0, mkl-service==2.3.0, mock==4.0.1, more-itertools==8.2.0, mpmath==1.1.0, msgpack==0.6.1, multipledispatch==0.6.0, nbconvert==5.6.1, nbformat==5.0.4, networkx==2.4, nltk==3.4.5, nodeenv==1.3.5, nose==1.3.7, notebook==6.0.3, ntlm-auth==1.4.0, numba==0.48.0, numexpr==2.7.1, numpy==1.18.1, numpydoc==0.9.2, oauthlib==3.1.0, olefile==0.46, openpyxl==3.0.3, opt-einsum==3.2.1, packaging==20.1, pandas==1.0.1, pandocfilters==1.4.2, paramiko==2.7.2, parso==0.5.2, partd==1.1.0, path==13.1.0, pathlib2==2.3.5, pathtools==0.1.2, patsy==0.5.1, pep8==1.7.1, pexpect==4.8.0, pickleshare==0.7.5, Pillow==7.0.0, pkginfo==1.5.0.1, pluggy==0.13.1, ply==3.11, poyo==0.5.0, pre-commit==2.7.1, prometheus-client==0.7.1, prompt-toolki
t==3.0.3, protobuf==3.11.3, psutil==5.6.7, ptyprocess==0.6.0, py==1.8.1, py4j==0.10.7, pyarrow==1.0.1, pyasn1==0.4.8, pyasn1-modules==0.2.8, pycodestyle==2.5.0, pycosat==0.6.3, pycparser==2.19, pycurl==7.43.0.5, pydocstyle==4.0.1, pyflakes==2.1.1, Pygments==2.5.2, pykerberos==1.2.1, pylint==2.4.4, PyNaCl==1.4.0, pyodbc===4.0.0-unsupported, pyOpenSSL==19.1.0, pypandoc==1.5, pyparsing==2.4.6, pyrsistent==0.15.7, PySocks==1.7.1, pyspark==2.4.5, pytest==5.3.5, pytest-arraydiff==0.2, pytest-astropy==0.8.0, pytest-astropy-header==0.1.2, pytest-doctestplus==0.5.0, pytest-openfiles==0.4.0, pytest-remotedata==0.3.2, python-dateutil==2.8.1, python-jsonrpc-server==0.3.4, python-language-server==0.31.7, python-slugify==4.0.0, pytz==2019.3, PyWavelets==1.1.1, pywinrm==0.4.1, pyxdg==0.26, PyYAML==5.3, pyzmq==18.1.1, QDarkStyle==2.8, QtAwesome==0.6.1, qtconsole==4.6.0, QtPy==1.9.0, requests==2.22.0, requests-futures==1.0.0, requests-kerberos==0.12.0, requests-ntlm==1.1.0, requests-oauthlib==1.3.0, rope==0.16.0, rsa==4.0, Rt
ree==0.9.3, ruamel-yaml==0.15.87, s3transfer==0.3.3, scikit-image==0.16.2, scikit-learn==0.23.2, scipy==1.4.1, seaborn==0.10.0, SecretStorage==3.1.2, Send2Trash==1.5.0, simplegeneric==0.8.1, singledispatch==3.4.0.3, sip==4.19.13, six==1.14.0, skein==0.8.0, smart-open==1.11.1, snowballstemmer==2.0.0, sortedcollections==1.1.1, sortedcontainers==2.1.0, soupsieve==1.9.5, spark-nlp==2.5.5, Sphinx==2.4.0, sphinxcontrib-applehelp==1.0.1, sphinxcontrib-devhelp==1.0.1, sphinxcontrib-htmlhelp==1.0.2, sphinxcontrib-jsmath==1.0.1, sphinxcontrib-qthelp==1.0.2, sphinxcontrib-serializinghtml==1.1.3, sphinxcontrib-websupport==1.2.0, spyder==4.0.1, spyder-kernels==1.8.1, SQLAlchemy==1.3.13, stanfordcorenlp==3.9.1.1, statsmodels==0.11.0, sympy==1.5.1, tables==3.6.1, tblib==1.6.0, tensorboard==2.3.0, tensorboard-plugin-wit==1.6.0.post3, tensorflow==2.3.0, tensorflow-estimator==2.3.0, termcolor==1.1.0, terminado==0.8.3, testpath==0.4.4, text-unidecode==1.3, threadpoolctl==2.1.0, thrift==0.13.0, thriftpy2==0.4.11, toml==0.10.0, t
oolz==0.10.0, tornado==6.0.3, tqdm==4.42.1, traitlets==4.3.3, ujson==1.35, unicodecsv==0.14.1, urllib3==1.25.8, virtualenv==20.0.18, watchdog==0.10.2, wcwidth==0.1.8, webencodings==0.5.1, Werkzeug==1.0.0, widgetsnbextension==3.5.1, wrapt==1.11.2, wurlitzer==2.0.0, xgboost==0.90, xlrd==1.2.0, XlsxWriter==1.2.7, xlwt==1.3.0, xmltodict==0.12.0, yapf==0.28.0, zict==1.0.0, zipp==2.2.0,
2020/09/14 11:28:18.948354132 Creating lockfile: python/requirements.txt.lock
Completed Python build against Python version: '3.8.1'
Launching Jupyter notebook...
2020/09/14 11:28:20.610519182 arguments: /mnt/share/conda/envs/kourou_rev1_python3.8/bin/python3.8 /opt/rstudio-connect/python/build_report.py
2020/09/14 11:28:20.610683278
2020/09/14 11:28:21.878736152
2020/09/14 11:28:21.878785967 CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
2020/09/14 11:28:21.878855706 To initialize your shell, run
2020/09/14 11:28:21.878861621
2020/09/14 11:28:21.878870665     $ conda init <SHELL_NAME>
2020/09/14 11:28:21.878871436
2020/09/14 11:28:21.878880537 Currently supported shells are:
2020/09/14 11:28:21.878881242   - bash
2020/09/14 11:28:21.878892535   - fish
2020/09/14 11:28:21.878893271   - tcsh
2020/09/14 11:28:21.878900975   - xonsh
2020/09/14 11:28:21.878901692   - zsh
2020/09/14 11:28:21.878909451   - powershell
2020/09/14 11:28:21.878910141
2020/09/14 11:28:21.878941144 See 'conda init --help' for more information and options.
2020/09/14 11:28:21.878948640
2020/09/14 11:28:21.878964698 IMPORTANT: You may need to close and restart your shell after running 'conda init'.
2020/09/14 11:28:21.878965598
2020/09/14 11:28:21.879031251
2020/09/14 11:28:22.088792231 Running on host: spaxd101.ecbt1.tadnet.net
2020/09/14 11:28:22.088830189 Bootstrapping environment using Python "3.8.1 (default, Jan  8 2020, 22:29:32)  [GCC 7.3.0]" at "/mnt/share/conda/envs/kourou_rev1_python3.8/bin/python3.8"
2020/09/14 11:28:22.089100723 Running as user: rstudio-connect
2020/09/14 11:28:23.623962834 Packages in the environment: absl-py==0.9.0, alabaster==0.7.12, anaconda-client==1.7.2, anaconda-project==0.8.3, appdirs==1.4.3, argh==0.26.2, arrow==0.15.5, asn1crypto==1.3.0, astroid==2.3.3, astropy==4.0, astunparse==1.6.3, atomicwrites==1.3.0, attrs==19.3.0, autopep8==1.4.4, Babel==2.8.0, backcall==0.1.0, backports.shutil-get-terminal-size==1.0.0, bcrypt==3.2.0, beautifulsoup4==4.8.2, binaryornot==0.4.4, bitarray==1.2.1, bkcharts==0.2, bleach==3.1.0, bokeh==1.4.0, boto==2.49.0, boto3==1.12.46, botocore==1.15.46, Bottleneck==1.3.2, cachetools==4.1.0, certifi==2019.11.28, cffi==1.14.0, cfgv==3.1.0, chardet==3.0.4, Click==7.0, cloudpickle==1.3.0, clyent==1.2.2, colorama==0.4.3, contextlib2==0.6.0.post1, cookiecutter==1.7.2, cryptography==2.8, cycler==0.10.0, Cython==0.29.15, cytoolz==0.10.1, dask==2.11.0, dask-glm==0.2.0, dask-ml==1.6.0, dask-tensorflow==0.0.2, dask-xgboost==0.1.11, dask-yarn==0.8.1, decorator==4.4.1, defusedxml==0.6.0, diff-match-patch==20181111, distlib==0.3.0, distributed==2.11.0, docutils==0.15.2, elephas==0.4.3, entrypoints==0.3, et-xmlfile==1.0.1, fastcache==1.1.0, filelock==3.0.12, flake8==3.7.9, Flask==1.1.1, fsspec==0.6.2, future==0.18.2, fuzzywuzzy==0.18.0, gast==0.3.3, gensim==3.8.3, gevent==1.3.7, glob2==0.7, gmpy2==2.0.8, google-auth==1.14.1, google-auth-oauthlib==0.4.1, google-pasta==0.2.0, graphframes==0.6, greenlet==0.4.15, grpcio==1.28.1, h5py==2.10.0, HeapDict==1.0.1, html5lib==1.0.1, hyperas==0.4.1, hyperopt==0.2.4, hypothesis==5.5.4, identify==1.4.15, idna==2.8, imageio==2.6.1, imagesize==1.2.0, importlib-metadata==1.5.0, impyla==0.16.2, intervaltree==3.0.2, ipykernel==5.1.4, ipython==7.12.0, ipython-genutils==0.2.0, ipywidgets==7.5.1, isort==4.3.21, itsdangerous==1.1.0, jdcal==1.4.1, jedi==0.14.1, jeepney==0.4.2, Jinja2==2.11.1, jinja2-time==0.2.0, jmespath==0.9.5, joblib==0.14.1, json5==0.9.1, jsonschema==3.2.0, jupyter==1.0.0, jupyter-client==5.3.4, jupyter-console==6.1.0, jupyter-core==4.6.1, jupyterlab==1.2.6, jupyterlab-server==1.0.6, Keras==2.4.3, Keras-Applications==1.0.8, Keras-Preprocessing==1.1.2, keyring==21.1.0, kiwisolver==1.0.1, lazy-object-proxy==1.4.3, libarchive-c==2.8, llvmlite==0.31.0, locket==0.2.0, lxml==4.5.0, Markdown==3.2.1, MarkupSafe==1.1.1, matplotlib==3.1.3, mccabe==0.6.1, mistune==0.8.4, mkl-fft==1.0.15, mkl-random==1.1.0, mkl-service==2.3.0, mock==4.0.1, more-itertools==8.2.0, mpmath==1.1.0, msgpack==0.6.1, multipledispatch==0.6.0, nbconvert==5.6.1, nbformat==5.0.4, networkx==2.4, nltk==3.4.5, nodeenv==1.3.5, nose==1.3.7, notebook==6.0.3, ntlm-auth==1.4.0, numba==0.48.0, numexpr==2.7.1, numpy==1.18.1, numpydoc==0.9.2, oauthlib==3.1.0, olefile==0.46, openpyxl==3.0.3, opt-einsum==3.2.1, packaging==20.1, pandas==1.0.1, pandocfilters==1.4.2, paramiko==2.7.2, parso==0.5.2, partd==1.1.0, path==13.1.0, pathlib2==2.3.5, pathtools==0.1.2, patsy==0.5.1, pep8==1.7.1, pexpect==4.8.0, pickleshare==0.7.5, Pillow==7.0.0, pkginfo==1.5.0.1, pluggy==0.13.1, ply==3.11, poyo==0.5.0, pre-commit==2.7.1, prometheus-client==0.7.1, prompt-toolkit==3.0.3, protobuf==3.11.3, psutil==5.6.7, ptyprocess==0.6.0, py==1.8.1, py4j==0.10.7, pyarrow==1.0.1, pyasn1==0.4.8, pyasn1-modules==0.2.8, pycodestyle==2.5.0, pycosat==0.6.3, pycparser==2.19, pycurl==7.43.0.5, pydocstyle==4.0.1, pyflakes==2.1.1, Pygments==2.5.2, pykerberos==1.2.1, pylint==2.4.4, PyNaCl==1.4.0, pyodbc===4.0.0-unsupported, pyOpenSSL==19.1.0, pypandoc==1.5, pyparsing==2.4.6, pyrsistent==0.15.7, PySocks==1.7.1, pyspark==2.4.5, pytest==5.3.5, pytest-arraydiff==0.2, pytest-astropy==0.8.0, pytest-astropy-header==0.1.2, pytest-doctestplus==0.5.0, pytest-openfiles==0.4.0, pytest-remotedata==0.3.2, python-dateutil==2.8.1, python-jsonrpc-server==0.3.4, python-language-server==0.31.7, python-slugify==4.0.0, pytz==2019.3, PyWavelets==1.1.1, pywinrm==0.4.1, pyxdg==0.26, PyYAML==5.3, pyzmq==18.1.1, QDarkStyle==2.8, QtAwesome==0.6.1, qtconsole==4.6.0, QtPy==1.9.0, requests==2.22.0, requests-futures==1.0.0, requests-kerberos==0.12.0, requests-ntlm==1.1.0, requests-oauthlib==1.3.0, rope==0.16.0, rsa==4.0, Rtree==0.9.3, ruamel-yaml==0.15.87, s3transfer==0.3.3, scikit-image==0.16.2, scikit-learn==0.23.2, scipy==1.4.1, seaborn==0.10.0, SecretStorage==3.1.2, Send2Trash==1.5.0, simplegeneric==0.8.1, singledispatch==3.4.0.3, sip==4.19.13, six==1.14.0, skein==0.8.0, smart-open==1.11.1, snowballstemmer==2.0.0, sortedcollections==1.1.1, sortedcontainers==2.1.0, soupsieve==1.9.5, spark-nlp==2.5.5, Sphinx==2.4.0, sphinxcontrib-applehelp==1.0.1, sphinxcontrib-devhelp==1.0.1, sphinxcontrib-htmlhelp==1.0.2, sphinxcontrib-jsmath==1.0.1, sphinxcontrib-qthelp==1.0.2, sphinxcontrib-serializinghtml==1.1.3, sphinxcontrib-websupport==1.2.0, spyder==4.0.1, spyder-kernels==1.8.1, SQLAlchemy==1.3.13, stanfordcorenlp==3.9.1.1, statsmodels==0.11.0, sympy==1.5.1, tables==3.6.1, tblib==1.6.0, tensorboard==2.3.0, tensorboard-plugin-wit==1.6.0.post3, tensorflow==2.3.0, tensorflow-estimator==2.3.0, termcolor==1.1.0, terminado==0.8.3, testpath==0.4.4, text-unidecode==1.3, threadpoolctl==2.1.0, thrift==0.13.0, thriftpy2==0.4.11, toml==0.10.0, toolz==0.10.0, tornado==6.0.3, tqdm==4.42.1, traitlets==4.3.3, ujson==1.35, unicodecsv==0.14.1, urllib3==1.25.8, virtualenv==20.0.18, watchdog==0.10.2, wcwidth==0.1.8, webencodings==0.5.1, Werkzeug==1.0.0, widgetsnbextension==3.5.1, wrapt==1.11.2, wurlitzer==2.0.0, xgboost==0.90, xlrd==1.2.0, XlsxWriter==1.2.7, xlwt==1.3.0, xmltodict==0.12.0, yapf==0.28.0, zict==1.0.0, zipp==2.2.0,
2020/09/14 11:28:25.040524285 Checking for jupyter using "/opt/rstudio-connect/mnt/app/python/env/bin/python -m jupyter --version"
2020/09/14 11:28:27.339729859 Checking for nbconvert using "/opt/rstudio-connect/mnt/app/python/env/bin/python -m nbconvert --version"
2020/09/14 11:28:28.731175180 Checking for ipykernel using "/opt/rstudio-connect/mnt/app/python/env/bin/python -m ipykernel --version"
2020/09/14 11:28:32.343057798 Found kernel `python-venv`: {'resource_dir': '/opt/rstudio-connect/mnt/app/python/env/share/jupyter/kernels/python-venv', 'spec': {'argv': ['/opt/rstudio-connect/mnt/app/python/env/bin/python', '-m', 'ipykernel_launcher', '-f', '{connection_file}'], 'env': {}, 'display_name': 'python-venv', 'language': 'python', 'interrupt_mode': 'signal', 'metadata': {}}}
2020/09/14 11:28:32.343100253 Building "stock-report-jupyter.ipynb" using kernel "python-venv"
2020/09/14 11:28:34.052812802 [NbConvertApp] Converting notebook stock-report-jupyter.ipynb to html
2020/09/14 11:28:36.798460677 [NbConvertApp] Executing notebook with kernel: python-venv
2020/09/14 11:28:43.721372801 [NbConvertApp] ERROR | Error while converting 'stock-report-jupyter.ipynb'
2020/09/14 11:28:43.721387194 Traceback (most recent call last):
2020/09/14 11:28:43.721564481   File "/mnt/share/conda/envs/kourou_rev1_python3.8/lib/python3.8/site-packages/nbconvert/nbconvertapp.py", line 410, in export_single_notebook
2020/09/14 11:28:43.721575535     output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
2020/09/14 11:28:43.721595294   File "/mnt/share/conda/envs/kourou_rev1_python3.8/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
2020/09/14 11:28:43.721597358     return self.from_file(f, resources=resources, **kw)
2020/09/14 11:28:43.721610400   File "/mnt/share/conda/envs/kourou_rev1_python3.8/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 197, in from_file
2020/09/14 11:28:43.721611447     return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
2020/09/14 11:28:43.721620466   File "/mnt/share/conda/envs/kourou_rev1_python3.8/lib/python3.8/site-packages/nbconvert/exporters/html.py", line 95, in from_notebook_node
2020/09/14 11:28:43.721621626     return super(HTMLExporter, self).from_notebook_node(nb, resources, **kw)
2020/09/14 11:28:43.721630475   File "/mnt/share/conda/envs/kourou_rev1_python3.8/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 307, in from_notebook_node
2020/09/14 11:28:43.721635788     nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
2020/09/14 11:28:43.721646940   File "/mnt/share/conda/envs/kourou_rev1_python3.8/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 139, in from_notebook_node
2020/09/14 11:28:43.721649518     nb_copy, resources = self._preprocess(nb_copy, resources)
2020/09/14 11:28:43.721665315   File "/mnt/share/conda/envs/kourou_rev1_python3.8/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 316, in _preprocess
2020/09/14 11:28:43.721668645     nbc, resc = preprocessor(nbc, resc)
2020/09/14 11:28:43.721691308   File "/mnt/share/conda/envs/kourou_rev1_python3.8/lib/python3.8/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
2020/09/14 11:28:43.721694714     return self.preprocess(nb, resources)
2020/09/14 11:28:43.721712288   File "/mnt/share/conda/envs/kourou_rev1_python3.8/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
2020/09/14 11:28:43.721714860     nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
2020/09/14 11:28:43.721738863   File "/mnt/share/conda/envs/kourou_rev1_python3.8/lib/python3.8/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
2020/09/14 11:28:43.721740705     nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
2020/09/14 11:28:43.721779077   File "/mnt/share/conda/envs/kourou_rev1_python3.8/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 448, in preprocess_cell
2020/09/14 11:28:43.721783151     raise CellExecutionError.from_cell_and_msg(cell, out)
2020/09/14 11:28:43.721808140 nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
2020/09/14 11:28:43.721810071 ------------------
2020/09/14 11:28:43.721831038 import datetime
2020/09/14 11:28:43.721836675 import gzip
2020/09/14 11:28:43.721855260
2020/09/14 11:28:43.721856437 import pandas as pd
2020/09/14 11:28:43.721864649 import matplotlib.pyplot as plt
2020/09/14 11:28:43.721865336
2020/09/14 11:28:43.721873403 %matplotlib inline
2020/09/14 11:28:43.721874230
2020/09/14 11:28:43.721881913 prices = pd.read_json(gzip.open('quandl-wiki-tsla.json.gz'), orient='split')
2020/09/14 11:28:43.721882724
2020/09/14 11:28:43.721890930 data=[
2020/09/14 11:28:43.721891698     [
2020/09/14 11:28:43.721899497         prices.last('1d')['High'].values[0],
2020/09/14 11:28:43.721900377         prices.last('1d')['Low'].values[0],
2020/09/14 11:28:43.721908160         prices.last('1d')['Volume'].values[0].round(),
2020/09/14 11:28:43.721908960     ],
2020/09/14 11:28:43.721917739     [
2020/09/14 11:28:43.721918707         prices.asfreq('D').rolling(window=52*7, min_periods=1).max().last('1d')['High'].values[0],
2020/09/14 11:28:43.721927014         prices.asfreq('D').rolling(window=52*7, min_periods=1).min().last('1d')['Low'].values[0],
2020/09/14 11:28:43.721927834         prices.asfreq('D').rolling(window=52*7, min_periods=1).mean().last('1d')['Volume'].values[0].round(),
2020/09/14 11:28:43.721936356     ]
2020/09/14 11:28:43.721937099 ]
2020/09/14 11:28:43.722022198
2020/09/14 11:28:43.722026244 pd.DataFrame(data, columns=['High', 'Low', 'Avg Volume'], index=['Most Recent Trading Day', '52-Week'])
2020/09/14 11:28:43.722042695 ------------------
2020/09/14 11:28:43.722043937
2020/09/14 11:28:43.722052393 ---------------------------------------------------------------------------
2020/09/14 11:28:43.722053357 FileNotFoundError                         Traceback (most recent call last)
2020/09/14 11:28:43.722062080 <ipython-input-1-dde53c9b6e9b> in <module>
2020/09/14 11:28:43.722062939       7 get_ipython().run_line_magic('matplotlib', 'inline')
2020/09/14 11:28:43.722079822       8
2020/09/14 11:28:43.722084529 ----> 9 prices = pd.read_json(gzip.open('quandl-wiki-tsla.json.gz'), orient='split')
2020/09/14 11:28:43.722097038      10
2020/09/14 11:28:43.722097963      11 data=[
2020/09/14 11:28:43.722106297
2020/09/14 11:28:43.722107108 /mnt/share/conda/envs/kourou_rev1_python3.8/lib/python3.8/gzip.py in open(filename, mode, compresslevel, encoding, errors, newline)
2020/09/14 11:28:43.722115096      56     gz_mode = mode.replace("t", "")
2020/09/14 11:28:43.722118591      57     if isinstance(filename, (str, bytes, os.PathLike)):
2020/09/14 11:28:43.722153657 ---> 58         binary_file = GzipFile(filename, gz_mode, compresslevel)
2020/09/14 11:28:43.722155238      59     elif hasattr(filename, "read") or hasattr(filename, "write"):
2020/09/14 11:28:43.722169685      60         binary_file = GzipFile(None, gz_mode, compresslevel, filename)
2020/09/14 11:28:43.722173692
2020/09/14 11:28:43.722182179 /mnt/share/conda/envs/kourou_rev1_python3.8/lib/python3.8/gzip.py in __init__(self, filename, mode, compresslevel, fileobj, mtime)
2020/09/14 11:28:43.722182974     171             mode += 'b'
2020/09/14 11:28:43.722191292     172         if fileobj is None:
2020/09/14 11:28:43.722197575 --> 173             fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
2020/09/14 11:28:43.722206630     174         if filename is None:
2020/09/14 11:28:43.722207380     175             filename = getattr(fileobj, 'name', '')
2020/09/14 11:28:43.722215325
2020/09/14 11:28:43.722216101 FileNotFoundError: [Errno 2] No such file or directory: 'quandl-wiki-tsla.json.gz'
2020/09/14 11:28:43.722223742 FileNotFoundError: [Errno 2] No such file or directory: 'quandl-wiki-tsla.json.gz'
2020/09/14 11:28:43.722224533
2020/09/14 11:28:43.958903064 Error(s) during cleanup=892
2020/09/14 11:28:43.958924599 Error during wipe - environment may remain
2020/09/14 11:28:43.959222886 nbconvert failed with exit code 1
2020/09/14 11:28:43.723282401 Error code: render-python-code-error

An error occurred while running Python code.

Possible causes:
* There is a bug in the Python code being deployed.
* The Python code depends on conditions that are not present in Connect.
* The Python code depends on a version of Python that is not configured in Connect.

Possible solutions:
* Correct bugs in the Python code, then deploy the corrected content.
  - The document rendering log in Connect contains details of the error.
  - For content published from the RStudio IDE, knitting the document in the IDE may also be helpful for debugging.
  - For content published from Jupyter, running the notebook locally may help to isolate the problem.
* Install a version of Python on the Connect server that matches the one being used by the client computer, then redeploy the content. You can identify the required Python version from the log messages above, which will contain an entry similar to this:
  > Bundle requested Python version 3.7.0; using /opt/python/3.5.7/bin/python which has version 3.5.7
  In this example, the client computer has Python 3.7.0 and the Connect server has Python version 3.5.7. The recommended solution would be to install Python version 3.7.0 on the Connect server alonside the existing 3.5.7 installation.
* If you have previously published this content, viewers will continue to see the last successful output until the error is resolved by republishing.

References:
* https://docs.rstudio.com/connect/user/content-settings/#content-logs
* https://support.rstudio.com/hc/en-us/articles/205612627-Debugging-with-RStudio
* https://support.rstudio.com/hc/en-us/articles/229998627-Why-does-my-app-work-locally-but-not-on-my-RStudio-Connect-server
* https://docs.rstudio.com/connect/admin/getting-started/#installation
* https://docs.rstudio.com/rsconnect-jupyter/index.html

2020/09/14 11:28:43.723282401 Additional data:
Message: 'FileNotFoundError: [Errno 2] No such file or directory: 'quandl-wiki-tsla.json.gz''
Found in the following log entry:
2020/09/14 11:28:43.722223742 FileNotFoundError: [Errno 2] No such file or directory: 'quandl-wiki-tsla.json.gz'
Error: Task exited with status 1.
`

**Comment by cmougan** [comment]
Including Extra Files (Clearly in teh documentation)
You can include extra files in the deployment bundle to make them available when your notebook is run by the RStudio Connect server. Just specify them on the command line after the notebook file:


rsconnect deploy notebook my-notebook.ipynb data.csv
